/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Entidad.ClsEProducto;
import Negocio.ClsNProducto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FrmConsultarProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmConsultarProducto
     */
    public FrmConsultarProducto() {
        initComponents();
        MtdListar();
    }

    DefaultTableModel modelo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsultarProducto = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();

        tbConsultarProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CÓDIGO", "NOMBRE", "STOCK", "PRECIO U."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbConsultarProducto);

        btnCancelar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSeleccionar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnSeleccionar.setText("SELECCIONAR");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSeleccionar))
                .addGap(0, 54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int filam = tbConsultarProducto.getSelectedRow();
        if (filam != -1) {
            int id = Integer.parseInt(tbConsultarProducto.getValueAt(filam, 0).toString());
            ClsNProducto Npro = new ClsNProducto();
            ClsEProducto pro = Npro.MtdBuscarProducto(id);
            FrmCompra.txtCodigoProducto.setText(pro.getCodigo());
            FrmCompra.txtNombreProducto.setText(pro.getNombre());
            FrmCompra.txtPrecioUnitario.setText(String.valueOf(pro.getPrecio_unitario()));

            int nfilas = FrmCompra.tbCompra.getRowCount();
            for (int i = 0; i < nfilas; i++) {
                String cod = FrmCompra.tbCompra.getValueAt(i, 0).toString();
                if (cod.equals(FrmCompra.txtCodigoProducto.getText())) {
                    int tcantidad = Integer.parseInt(FrmCompra.tbCompra.getValueAt(i, 2).toString());
                    pro.setCantidad(pro.getCantidad() - tcantidad);
                    break;
                }
            }
            FrmCompra.txtStock.setText(String.valueOf(pro.getCantidad()));

            FrmCompra.btnAgregar.setEnabled(true);
            FrmCompra.btnQuitarTodo.setEnabled(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "SELECCIONA UNA FILA");
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbConsultarProducto;
    // End of variables declaration//GEN-END:variables

    private void MtdListar() {
        ClsNProducto objNE = new ClsNProducto();
        String[] datos = new String[7];
        LimpiarTabla();
        for (ClsEProducto objE : objNE.MtdListarProducto()) {
            if (objE.isEstado()) {
                datos[0] = String.valueOf(objE.getId_producto());
                datos[1] = objE.getCodigo();
                datos[2] = objE.getNombre();
                datos[3] = String.valueOf(objE.getCantidad());
                datos[4] = String.valueOf(objE.getPrecio_unitario());
                modelo.addRow(datos);
            }

        }
        this.tbConsultarProducto.setModel(modelo);
    }

    private void LimpiarTabla() {
        modelo = (DefaultTableModel) tbConsultarProducto.getModel();
        modelo.setRowCount(0);
    }
}
