/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Entidad.ClsECompra;
import Entidad.ClsEDetalleCompra;
import Negocio.ClsNCompra;
import Negocio.ClsNDetalleCompra;
import Negocio.ClsNProducto;
import java.beans.PropertyVetoException;
import static java.time.LocalDateTime.now;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FrmCompra extends javax.swing.JInternalFrame {

    public static String[] prueba = new String[20];
    DefaultTableModel modelo;

    public FrmCompra() {
        initComponents();
        modelo = (DefaultTableModel) tbCompra.getModel();
        txtFecha.setText(now().toString());
        try {
            this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
            BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
            bui.setNorthPane(null);
            this.setMaximum(true);
        } catch (PropertyVetoException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        SpnCantidadComprar = new javax.swing.JSpinner();
        txtPrecioUnitario = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        txtCodigoProducto = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnBuscarProveedor1 = new javax.swing.JButton();
        txtRazonSocial = new javax.swing.JTextField();
        txtRUC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCompra = new javax.swing.JTable();
        btnGenerar = new javax.swing.JButton();
        lblTotalPagar = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();

        label1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        label1.setText("Fecha");

        txtFecha.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtFecha.setDisabledTextColor(new java.awt.Color(51, 0, 0));
        txtFecha.setEnabled(false);

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnAgregar.setText("AGREGAR");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnQuitar.setText("QUITAR");
        btnQuitar.setEnabled(false);
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DE PRODUCTO"));

        SpnCantidadComprar.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        txtPrecioUnitario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtPrecioUnitario.setDisabledTextColor(new java.awt.Color(51, 0, 0));
        txtPrecioUnitario.setEnabled(false);

        txtNombreProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtNombreProducto.setDisabledTextColor(new java.awt.Color(51, 0, 0));
        txtNombreProducto.setEnabled(false);

        btnBuscarProducto.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnBuscarProducto.setText("...");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        txtCodigoProducto.setEditable(false);
        txtCodigoProducto.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txtCodigoProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        txtStock.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtStock.setDisabledTextColor(new java.awt.Color(51, 0, 0));
        txtStock.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SpnCantidadComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpnCantidadComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DE COMPRA"));

        btnBuscarProveedor1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnBuscarProveedor1.setText("...");
        btnBuscarProveedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveedor1ActionPerformed(evt);
            }
        });

        txtRazonSocial.setEditable(false);
        txtRazonSocial.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txtRazonSocial.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        txtRUC.setEditable(false);
        txtRUC.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txtRUC.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        tbCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "PRODUCTO", "CANTIDAD", "PRECIO U.", "SUBTOTAL"
            }
        ));
        jScrollPane1.setViewportView(tbCompra);

        btnGenerar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnGenerar.setText("GENERAR VENTA");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        lblTotalPagar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblTotalPagar.setText("TOTAL A PAGAR:");

        txtTotalPagar.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txtTotalPagar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalPagar.setText("0.0");
        txtTotalPagar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtTotalPagar.setDisabledTextColor(new java.awt.Color(51, 0, 0));
        txtTotalPagar.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGenerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1)
                        .addGap(18, 18, 18)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregar)
                            .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPagar)
                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        MtdLimpiar();
        btnAgregar.setEnabled(false);
        btnQuitar.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int cantidadc = (int) (SpnCantidadComprar.getValue());
        int stock = Integer.parseInt(txtStock.getText());
        if (stock >= cantidadc) {
            boolean productoentabla = false;
            int nrofila = 5;
            for (int i = 0; i < tbCompra.getRowCount(); i++) {
                String codigo = tbCompra.getValueAt(i, 0).toString();
                if (codigo.equals(txtCodigoProducto.getText())) {
                    productoentabla = true;
                    nrofila = i;
                    break;
                }
            }

            double preciouni = Double.parseDouble(txtPrecioUnitario.getText());
            double total = Double.parseDouble(txtTotalPagar.getText());
            double subtotal = cantidadc * preciouni;
            if (productoentabla) {
                int tcantidad = Integer.parseInt(tbCompra.getValueAt(nrofila, 2).toString());
                double tsubtotal = Double.parseDouble(tbCompra.getValueAt(nrofila, 4).toString());

                int nuevacant = cantidadc + tcantidad;
                double nuevosub = tsubtotal + subtotal;

                tbCompra.setValueAt(nuevacant, nrofila, 2);
                tbCompra.setValueAt(nuevosub, nrofila, 4);

            } else {
                prueba[0] = txtCodigoProducto.getText();
                prueba[1] = txtNombreProducto.getText();
                prueba[2] = String.valueOf(cantidadc);
                prueba[3] = String.valueOf(preciouni);
                prueba[4] = String.valueOf(subtotal);
                modelo.addRow(prueba);
            }

            // Actualizar total a pagar
            double nuevototal = total + subtotal;
            txtTotalPagar.setText(String.valueOf(nuevototal));

            // Actualizar stock
            int nuevostock = stock - cantidadc;
            txtStock.setText(String.valueOf(nuevostock));
        } else {
            JOptionPane.showMessageDialog(null, "La Cantidad a comprar no debe ser mayor al stock");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        int filam;
        filam = tbCompra.getSelectedRow();
        if (filam != -1) {
            String codigo = tbCompra.getValueAt(filam, 0).toString();
            if (codigo.equals(prueba[0])) {
                int stock = Integer.parseInt(txtStock.getText());
                int cantidad = Integer.parseInt(tbCompra.getValueAt(filam, 2).toString());
                double subtotal = Double.parseDouble(tbCompra.getValueAt(filam, 4).toString());
                double total = Double.parseDouble(txtTotalPagar.getText());

                int nstock = stock + cantidad;
                double ntotal = total - subtotal;
                txtStock.setText(String.valueOf(nstock));
                txtTotalPagar.setText(String.valueOf(ntotal));
                modelo.removeRow(filam);
            }
        } else {
            JOptionPane.showMessageDialog(null, "SELECCIONA UNA FILA");
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        FrmConsultarProducto frm = new FrmConsultarProducto();
        Principal.dpPrincipal.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnBuscarProveedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedor1ActionPerformed
        FrmConsultarProveedor frm = new FrmConsultarProveedor();
        Principal.dpPrincipal.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_btnBuscarProveedor1ActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // COMPRA
        ClsECompra objEC = new ClsECompra();
        ClsNCompra objNC = new ClsNCompra();
        objEC.setTotal(Double.parseDouble(txtTotalPagar.getText()));
        objEC.setId_empleado(Principal.IdEmpleado2);
        objEC.setId_proveedor(Principal.IdProveedor2);

        if (objNC.MtdResgistrarCompra(objEC)) {
            JOptionPane.showMessageDialog(null, "VENTA AGREGADA");
            btnAgregar.setEnabled(false);
            btnQuitar.setEnabled(false);
            //            Principal.montocaja = Principal.montocaja + objEE.getTotalPagar();
            //            FrmCaja.txtMonto.setText(String.valueOf(Principal.montocaja));
        } else {
            JOptionPane.showMessageDialog(null, "NO SE PUDO GUARDAR DATOS");
            return;
        }

        // DETALLE DE COMPRA
        ClsEDetalleCompra objED = new ClsEDetalleCompra();
        ClsNDetalleCompra objND = new ClsNDetalleCompra();
        ClsNProducto objNP = new ClsNProducto();
        int nfilas = tbCompra.getRowCount();
        for (int i = 0; i < nfilas; i++) {
            String codigo = tbCompra.getValueAt(i, 0).toString();
            objED.setCantidad(Integer.parseInt(tbCompra.getValueAt(i, 2).toString()));
            objED.setProducto(objNP.BuscarProductoPorCodigo(codigo));
            objED.setSubtotal(Double.parseDouble(tbCompra.getValueAt(i, 4).toString()));
            objED.setCompra(new ClsECompra());
            objED.getCompra().setId_compra(objNC.MtdBuscarUltimaCompra());
            if (!objND.MtdResgistrarDetalle(objED)) {
                JOptionPane.showMessageDialog(null, "NO SE PUDO GUARDAR DATOS");
                return;
            }
        }
        MtdLimpiar();
    }//GEN-LAST:event_btnGenerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpnCantidadComprar;
    protected static javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnBuscarProveedor1;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnNuevo;
    protected static javax.swing.JButton btnQuitar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lblTotalPagar;
    protected static javax.swing.JTable tbCompra;
    public static javax.swing.JTextField txtCodigoProducto;
    public static javax.swing.JTextField txtFecha;
    static javax.swing.JTextField txtNombreProducto;
    public static javax.swing.JTextField txtPrecioUnitario;
    public static javax.swing.JTextField txtRUC;
    public static javax.swing.JTextField txtRazonSocial;
    public static javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
    
    private void MtdLimpiar() {
        SpnCantidadComprar.setValue(1);
        txtRazonSocial.setText("");
        txtCodigoProducto.setText("");
        txtPrecioUnitario.setText("");
        txtRUC.setText("");
        txtStock.setText("");
        txtTotalPagar.setText("0.0");
        txtNombreProducto.setText("");
        LimpiarTabla();
    }

    private void LimpiarTabla() {
        modelo = (DefaultTableModel) tbCompra.getModel();
        modelo.setRowCount(0);
    }
}
