/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Entidad.ClsEDetalleVenta;
import Entidad.ClsEVenta;
import Negocio.ClsNDetalleVenta;
import Negocio.ClsNProducto;
import Negocio.ClsNVenta;
import java.beans.PropertyVetoException;
import static java.time.LocalDateTime.now;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmVenta extends javax.swing.JInternalFrame {

    public static String[] prueba = new String[20];
    DefaultTableModel modelo;

    public FrmVenta() {
        initComponents();
        modelo = (DefaultTableModel) tbVenta.getModel();
        txtFecha.setText(now().toString());
        try {
            this.setMaximum(true);

        } catch (PropertyVetoException e) {
        }

//        llenarcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbVenta = new javax.swing.JTable();
        plDatosVenta = new javax.swing.JPanel();
        txtNombreCliente = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        lblCliente1 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        lblNVenta = new javax.swing.JLabel();
        plDatosProducto = new javax.swing.JPanel();
        txtCodigoProducto = new javax.swing.JTextField();
        lblCodigoBarras = new javax.swing.JLabel();
        btnBuscarProducto = new javax.swing.JButton();
        lblStock = new javax.swing.JLabel();
        lblVenta = new javax.swing.JLabel();
        txtPrecioUnitario = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        SpnCantidadComprar = new javax.swing.JSpinner();
        lblTotalPagar = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        tbVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "PRODUCTO", "CANTIDAD", "PRECIO U.", "SUBTOTAL"
            }
        ));
        jScrollPane1.setViewportView(tbVenta);

        plDatosVenta.setBackground(new java.awt.Color(153, 153, 153));
        plDatosVenta.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DE LA VENTA"));
        plDatosVenta.setOpaque(false);

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txtNombreCliente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        lblCliente.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblCliente.setText("Dni Cliente");

        btnBuscarCliente.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnBuscarCliente.setText("...");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        lblCliente1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblCliente1.setText("Nombre");

        txtDni.setEditable(false);
        txtDni.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txtDni.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        txtFecha.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtFecha.setDisabledTextColor(new java.awt.Color(51, 0, 0));
        txtFecha.setEnabled(false);

        lblNVenta.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblNVenta.setText("Fecha");

        javax.swing.GroupLayout plDatosVentaLayout = new javax.swing.GroupLayout(plDatosVenta);
        plDatosVenta.setLayout(plDatosVentaLayout);
        plDatosVentaLayout.setHorizontalGroup(
            plDatosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDatosVentaLayout.createSequentialGroup()
                .addGroup(plDatosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plDatosVentaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plDatosVentaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(plDatosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente)
                            .addComponent(lblCliente1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(plDatosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plDatosVentaLayout.createSequentialGroup()
                                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plDatosVentaLayout.setVerticalGroup(
            plDatosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDatosVentaLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(plDatosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNVenta)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(plDatosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(plDatosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente1)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        plDatosProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DEL PRODUCTO"));

        txtCodigoProducto.setEditable(false);
        txtCodigoProducto.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txtCodigoProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        lblCodigoBarras.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblCodigoBarras.setText("Código");

        btnBuscarProducto.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnBuscarProducto.setText("...");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        lblStock.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblStock.setText("Stock");

        lblVenta.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblVenta.setText("Precio Unitario");

        txtPrecioUnitario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtPrecioUnitario.setDisabledTextColor(new java.awt.Color(51, 0, 0));
        txtPrecioUnitario.setEnabled(false);

        lblNombre1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblNombre1.setText("Nombre");

        txtNombreProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtNombreProducto.setDisabledTextColor(new java.awt.Color(51, 0, 0));
        txtNombreProducto.setEnabled(false);

        lblCantidad.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblCantidad.setText("Cantidad a Comprar");

        txtStock.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtStock.setDisabledTextColor(new java.awt.Color(51, 0, 0));
        txtStock.setEnabled(false);

        SpnCantidadComprar.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout plDatosProductoLayout = new javax.swing.GroupLayout(plDatosProducto);
        plDatosProducto.setLayout(plDatosProductoLayout);
        plDatosProductoLayout.setHorizontalGroup(
            plDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDatosProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, plDatosProductoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(plDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantidad)
                            .addComponent(lblNombre1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpnCantidadComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(plDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVenta)
                            .addComponent(lblStock))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(plDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, plDatosProductoLayout.createSequentialGroup()
                        .addComponent(lblCodigoBarras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        plDatosProductoLayout.setVerticalGroup(
            plDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDatosProductoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(plDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoBarras)
                    .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(plDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVenta)
                        .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombre1)))
                .addGap(19, 19, 19)
                .addGroup(plDatosProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStock)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpnCantidadComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        lblTotalPagar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblTotalPagar.setText("TOTAL A PAGAR");

        txtTotalPagar.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        txtTotalPagar.setText("0.0");
        txtTotalPagar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txtTotalPagar.setDisabledTextColor(new java.awt.Color(51, 0, 0));
        txtTotalPagar.setEnabled(false);

        btnGenerar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnGenerar.setText("GENERAR VENTA");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnQuitar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnQuitar.setText("QUITAR");
        btnQuitar.setEnabled(false);
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        jButton1.setText("Ultima Venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotalPagar)
                                .addGap(30, 30, 30)
                                .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plDatosVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plDatosProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(plDatosVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(plDatosProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalPagar)
                            .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(38, 38, 38))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        FrmConsultarCliente frm = new FrmConsultarCliente();
        Principal.dpPrincipal.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // VENTA
        ClsEVenta objEV = new ClsEVenta();
        ClsNVenta objNV = new ClsNVenta();
        objEV.setTotal(Double.parseDouble(txtTotalPagar.getText()));
        objEV.setId_empleado(Principal.IdEmpleado2);
        objEV.setId_cliente(Principal.IdCliente2);

        if (objNV.MtdResgistrarVenta(objEV)) {
            JOptionPane.showMessageDialog(null, "VENTA AGREGADA");
            btnAgregar.setEnabled(false);
            btnQuitar.setEnabled(false);
//            Principal.montocaja = Principal.montocaja + objEE.getTotalPagar();
//            FrmCaja.txtMonto.setText(String.valueOf(Principal.montocaja));
        } 
        else {
            JOptionPane.showMessageDialog(null, "NO SE PUDO GUARDAR DATOS");
            return;
        }

        // DETALLE DE VENTA
        ClsEDetalleVenta objED = new ClsEDetalleVenta();
        ClsNDetalleVenta objND = new ClsNDetalleVenta();
        ClsNProducto objNP = new ClsNProducto();
        int nfilas = tbVenta.getRowCount();
        for (int i = 0; i < nfilas; i++) {
            String codigo = tbVenta.getValueAt(i, 0).toString();
            objED.setCantidad(Integer.parseInt(tbVenta.getValueAt(i, 2).toString()));
            objED.setProducto(objNP.BuscarProductoPorCodigo(codigo));
            objED.setSubtotal(Double.parseDouble(tbVenta.getValueAt(i, 4).toString()));
            objED.setVenta(new ClsEVenta());
            objED.getVenta().setId_venta(objNV.MtdBuscarUltimaVenta());
            if (!objND.MtdResgistrarDetalle(objED)) {
                JOptionPane.showMessageDialog(null, "NO SE PUDO GUARDAR DATOS");
                return;
            }
        }
        MtdLimpiar();

    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        MtdLimpiar();
        btnAgregar.setEnabled(false);
        btnQuitar.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int cantidadc = (int) (SpnCantidadComprar.getValue());
        int stock = Integer.parseInt(txtStock.getText());
        if (stock >= cantidadc) {
            boolean productoentabla = false;
            int nrofila = 5;
            for (int i = 0; i < tbVenta.getRowCount(); i++) {
                String codigo = tbVenta.getValueAt(i, 0).toString();
                if (codigo.equals(txtCodigoProducto.getText())) {
                    productoentabla = true;
                    nrofila = i;
                    break;
                }
            }

            double preciouni = Double.parseDouble(txtPrecioUnitario.getText());
            double total = Double.parseDouble(txtTotalPagar.getText());
            double subtotal = cantidadc * preciouni;
            if (productoentabla) {
                int tcantidad = Integer.parseInt(tbVenta.getValueAt(nrofila, 2).toString());
                double tsubtotal = Double.parseDouble(tbVenta.getValueAt(nrofila, 4).toString());

                int nuevacant = cantidadc + tcantidad;
                double nuevosub = tsubtotal + subtotal;

                tbVenta.setValueAt(nuevacant, nrofila, 2);
                tbVenta.setValueAt(nuevosub, nrofila, 4);

            } else {
                prueba[0] = txtCodigoProducto.getText();
                prueba[1] = txtNombreProducto.getText();
                prueba[2] = String.valueOf(cantidadc);
                prueba[3] = String.valueOf(preciouni);
                prueba[4] = String.valueOf(subtotal);
                modelo.addRow(prueba);
            }

            // Actualizar total a pagar
            double nuevototal = total + subtotal;
            txtTotalPagar.setText(String.valueOf(nuevototal));

            // Actualizar stock
            int nuevostock = stock - cantidadc;
            txtStock.setText(String.valueOf(nuevostock));
        } else {
            JOptionPane.showMessageDialog(null, "La Cantidad a comprar no debe ser mayor al stock");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        int filam;
        filam = tbVenta.getSelectedRow();
        if (filam != -1) {
            String codigo = tbVenta.getValueAt(filam, 0).toString();
            if (codigo.equals(prueba[0])) {
                int stock = Integer.parseInt(txtStock.getText());
                int cantidad = Integer.parseInt(tbVenta.getValueAt(filam, 2).toString());
                double subtotal = Double.parseDouble(tbVenta.getValueAt(filam, 4).toString());
                double total = Double.parseDouble(txtTotalPagar.getText());

                int nstock = stock + cantidad;
                double ntotal = total - subtotal;
                txtStock.setText(String.valueOf(nstock));
                txtTotalPagar.setText(String.valueOf(ntotal));
                modelo.removeRow(filam);
            }
        } else {
            JOptionPane.showMessageDialog(null, "SELECCIONA UNA FILA");
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        FrmConsultarProducto frm = new FrmConsultarProducto();
        Principal.dpPrincipal.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClsNVenta objNV = new ClsNVenta();
        System.out.println(objNV.MtdBuscarUltimaVenta());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpnCantidadComprar;
    protected static javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnNuevo;
    protected static javax.swing.JButton btnQuitar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCliente1;
    private javax.swing.JLabel lblCodigoBarras;
    private javax.swing.JLabel lblNVenta;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTotalPagar;
    private javax.swing.JLabel lblVenta;
    private javax.swing.JPanel plDatosProducto;
    private javax.swing.JPanel plDatosVenta;
    protected static javax.swing.JTable tbVenta;
    public static javax.swing.JTextField txtCodigoProducto;
    public static javax.swing.JTextField txtDni;
    public static javax.swing.JTextField txtFecha;
    public static javax.swing.JTextField txtNombreCliente;
    static javax.swing.JTextField txtNombreProducto;
    public static javax.swing.JTextField txtPrecioUnitario;
    public static javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables

    private void MtdLimpiar() {
        SpnCantidadComprar.setValue(1);
        txtNombreCliente.setText("");
        txtCodigoProducto.setText("");
        txtPrecioUnitario.setText("");
        txtDni.setText("");
        txtStock.setText("");
        txtTotalPagar.setText("0.0");
        txtNombreProducto.setText("");
        LimpiarTabla();
    }

    private void LimpiarTabla() {
        modelo = (DefaultTableModel) tbVenta.getModel();
        modelo.setRowCount(0);
    }

}
