/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {

    public static int codigoproducto;
    public static int IdEmpleado2, IdCliente2, IdProveedor2;
    Color color = new Color(210, 210, 210);

    public Principal(String dni, String Tipo, String Nombre, String IdEmpleado) {
        initComponents();
        lblDni.setText(FrmLogin.puente);
        lblTipo.setText(FrmLogin.puente2);
        lblNombre.setText(FrmLogin.puente3);
        IdEmpleado2 = Integer.parseInt(IdEmpleado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        jpBarraLateral = new javax.swing.JPanel();
        jpMantenimiento = new javax.swing.JPanel();
        lblmantenimiento = new javax.swing.JLabel();
        jpSalir = new javax.swing.JPanel();
        txtBtnSalir = new javax.swing.JLabel();
        jpEmpleados = new javax.swing.JPanel();
        txtBtnEmpleados = new javax.swing.JLabel();
        jpProveedores = new javax.swing.JPanel();
        txtBtnProveedores = new javax.swing.JLabel();
        jpCompras = new javax.swing.JPanel();
        txtBtnCompras = new javax.swing.JLabel();
        jpReportes = new javax.swing.JPanel();
        lblmantenimiento1 = new javax.swing.JLabel();
        jpIngresosDiarios = new javax.swing.JPanel();
        txtBtnIngresosDiarios = new javax.swing.JLabel();
        jpIngresosDiarios1 = new javax.swing.JPanel();
        txtBtnIngresosDiarios3 = new javax.swing.JLabel();
        jpIngresosDiarios2 = new javax.swing.JPanel();
        txtBtnIngresosDiarios4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dpPrincipal = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpHeader.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tienda de Videojuegos - Drasha Games Store");

        lblTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setText("jLabel5");

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("jLabel4");

        lblDni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDni.setForeground(new java.awt.Color(255, 255, 255));
        lblDni.setText("jLabel1");

        javax.swing.GroupLayout jpHeaderLayout = new javax.swing.GroupLayout(jpHeader);
        jpHeader.setLayout(jpHeaderLayout);
        jpHeaderLayout.setHorizontalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDni)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addGap(18, 18, 18)
                .addComponent(lblTipo)
                .addGap(44, 44, 44))
        );
        jpHeaderLayout.setVerticalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addGroup(jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpBarraLateral.setBackground(new java.awt.Color(231, 231, 231));
        jpBarraLateral.setPreferredSize(new java.awt.Dimension(280, 677));

        jpMantenimiento.setBackground(new java.awt.Color(239, 238, 244));

        lblmantenimiento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblmantenimiento.setForeground(new java.awt.Color(128, 128, 131));
        lblmantenimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmantenimiento.setText("Mantenimiento");

        javax.swing.GroupLayout jpMantenimientoLayout = new javax.swing.GroupLayout(jpMantenimiento);
        jpMantenimiento.setLayout(jpMantenimientoLayout);
        jpMantenimientoLayout.setHorizontalGroup(
            jpMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMantenimientoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblmantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpMantenimientoLayout.setVerticalGroup(
            jpMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMantenimientoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblmantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpSalir.setBackground(new java.awt.Color(239, 238, 244));

        txtBtnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBtnSalir.setForeground(new java.awt.Color(128, 128, 131));
        txtBtnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBtnSalir.setText("SALIR");
        txtBtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBtnSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpSalirLayout = new javax.swing.GroupLayout(jpSalir);
        jpSalir.setLayout(jpSalirLayout);
        jpSalirLayout.setHorizontalGroup(
            jpSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpSalirLayout.setVerticalGroup(
            jpSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpEmpleados.setBackground(new java.awt.Color(249, 249, 249));

        txtBtnEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBtnEmpleados.setForeground(new java.awt.Color(153, 153, 153));
        txtBtnEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBtnEmpleados.setText("EMPLEADOS");
        txtBtnEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBtnEmpleadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBtnEmpleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBtnEmpleadosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpEmpleadosLayout = new javax.swing.GroupLayout(jpEmpleados);
        jpEmpleados.setLayout(jpEmpleadosLayout);
        jpEmpleadosLayout.setHorizontalGroup(
            jpEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEmpleadosLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtBtnEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpEmpleadosLayout.setVerticalGroup(
            jpEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEmpleadosLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtBtnEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jpProveedores.setBackground(new java.awt.Color(249, 249, 249));

        txtBtnProveedores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBtnProveedores.setForeground(new java.awt.Color(153, 153, 153));
        txtBtnProveedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBtnProveedores.setText("PROVEEDORES");
        txtBtnProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBtnProveedoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBtnProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBtnProveedoresMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpProveedoresLayout = new javax.swing.GroupLayout(jpProveedores);
        jpProveedores.setLayout(jpProveedoresLayout);
        jpProveedoresLayout.setHorizontalGroup(
            jpProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBtnProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpProveedoresLayout.setVerticalGroup(
            jpProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBtnProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        jpCompras.setBackground(new java.awt.Color(249, 249, 249));

        txtBtnCompras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBtnCompras.setForeground(new java.awt.Color(153, 153, 153));
        txtBtnCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBtnCompras.setText("COMPRAS");
        txtBtnCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBtnComprasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBtnComprasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBtnComprasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpComprasLayout = new javax.swing.GroupLayout(jpCompras);
        jpCompras.setLayout(jpComprasLayout);
        jpComprasLayout.setHorizontalGroup(
            jpComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBtnCompras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpComprasLayout.setVerticalGroup(
            jpComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBtnCompras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        jpReportes.setBackground(new java.awt.Color(239, 238, 244));

        lblmantenimiento1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblmantenimiento1.setForeground(new java.awt.Color(128, 128, 131));
        lblmantenimiento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmantenimiento1.setText("Reportes");

        javax.swing.GroupLayout jpReportesLayout = new javax.swing.GroupLayout(jpReportes);
        jpReportes.setLayout(jpReportesLayout);
        jpReportesLayout.setHorizontalGroup(
            jpReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmantenimiento1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        jpReportesLayout.setVerticalGroup(
            jpReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpReportesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblmantenimiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jpIngresosDiarios.setBackground(new java.awt.Color(249, 249, 249));

        txtBtnIngresosDiarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBtnIngresosDiarios.setForeground(new java.awt.Color(153, 153, 153));
        txtBtnIngresosDiarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBtnIngresosDiarios.setText("INGRESOS DIARIOS");
        txtBtnIngresosDiarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBtnIngresosDiariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBtnIngresosDiariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBtnIngresosDiariosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpIngresosDiariosLayout = new javax.swing.GroupLayout(jpIngresosDiarios);
        jpIngresosDiarios.setLayout(jpIngresosDiariosLayout);
        jpIngresosDiariosLayout.setHorizontalGroup(
            jpIngresosDiariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBtnIngresosDiarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpIngresosDiariosLayout.setVerticalGroup(
            jpIngresosDiariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBtnIngresosDiarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        jpIngresosDiarios1.setBackground(new java.awt.Color(249, 249, 249));

        txtBtnIngresosDiarios3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBtnIngresosDiarios3.setForeground(new java.awt.Color(153, 153, 153));
        txtBtnIngresosDiarios3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBtnIngresosDiarios3.setText("INGRESOS DIARIOS");
        txtBtnIngresosDiarios3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBtnIngresosDiarios3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBtnIngresosDiarios3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBtnIngresosDiarios3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpIngresosDiarios1Layout = new javax.swing.GroupLayout(jpIngresosDiarios1);
        jpIngresosDiarios1.setLayout(jpIngresosDiarios1Layout);
        jpIngresosDiarios1Layout.setHorizontalGroup(
            jpIngresosDiarios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBtnIngresosDiarios3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpIngresosDiarios1Layout.setVerticalGroup(
            jpIngresosDiarios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBtnIngresosDiarios3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        jpIngresosDiarios2.setBackground(new java.awt.Color(249, 249, 249));

        txtBtnIngresosDiarios4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBtnIngresosDiarios4.setForeground(new java.awt.Color(153, 153, 153));
        txtBtnIngresosDiarios4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBtnIngresosDiarios4.setText("INGRESOS DIARIOS");
        txtBtnIngresosDiarios4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBtnIngresosDiarios4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBtnIngresosDiarios4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBtnIngresosDiarios4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpIngresosDiarios2Layout = new javax.swing.GroupLayout(jpIngresosDiarios2);
        jpIngresosDiarios2.setLayout(jpIngresosDiarios2Layout);
        jpIngresosDiarios2Layout.setHorizontalGroup(
            jpIngresosDiarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBtnIngresosDiarios4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpIngresosDiarios2Layout.setVerticalGroup(
            jpIngresosDiarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBtnIngresosDiarios4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpBarraLateralLayout = new javax.swing.GroupLayout(jpBarraLateral);
        jpBarraLateral.setLayout(jpBarraLateralLayout);
        jpBarraLateralLayout.setHorizontalGroup(
            jpBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpIngresosDiarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpIngresosDiarios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpIngresosDiarios2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpBarraLateralLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpBarraLateralLayout.setVerticalGroup(
            jpBarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBarraLateralLayout.createSequentialGroup()
                .addComponent(jpMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpIngresosDiarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpIngresosDiarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpIngresosDiarios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(941, 635));

        dpPrincipal.setPreferredSize(new java.awt.Dimension(942, 635));

        javax.swing.GroupLayout dpPrincipalLayout = new javax.swing.GroupLayout(dpPrincipal);
        dpPrincipal.setLayout(dpPrincipalLayout);
        dpPrincipalLayout.setHorizontalGroup(
            dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        dpPrincipalLayout.setVerticalGroup(
            dpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(dpPrincipal);

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpBarraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jpHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpBarraLateral, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addComponent(pnlCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBtnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnSalirMouseClicked
        FrmLogin login = new FrmLogin();
        login.show();
        this.dispose();
    }//GEN-LAST:event_txtBtnSalirMouseClicked

    private void txtBtnEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnEmpleadosMouseClicked
        dpPrincipal.removeAll();
        FrmEmpleado pnlEmpleado = new FrmEmpleado();
        dpPrincipal.add(pnlEmpleado).setVisible(true);
        jpEmpleados.setBackground(new Color(210, 210, 210));

        jpProveedores.setBackground(new java.awt.Color(249, 249, 249));
        txtBtnProveedores.setForeground(new java.awt.Color(153, 153, 153));
        jpCompras.setBackground(new java.awt.Color(249, 249, 249));
        txtBtnCompras.setForeground(new java.awt.Color(153, 153, 153));
        jpIngresosDiarios.setBackground(new java.awt.Color(249, 249, 249));
        txtBtnIngresosDiarios.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_txtBtnEmpleadosMouseClicked

    private void txtBtnProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnProveedoresMouseClicked
        dpPrincipal.removeAll();
        FrmProveedor pnlProveedor = new FrmProveedor();
        dpPrincipal.add(pnlProveedor).setVisible(true);
        jpProveedores.setBackground(new Color(210, 210, 210));

        jpEmpleados.setBackground(new java.awt.Color(249, 249, 249));
        txtBtnEmpleados.setForeground(new java.awt.Color(153, 153, 153));
        jpCompras.setBackground(new java.awt.Color(249, 249, 249));
        txtBtnCompras.setForeground(new java.awt.Color(153, 153, 153));
        jpIngresosDiarios.setBackground(new java.awt.Color(249, 249, 249));
        txtBtnIngresosDiarios.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_txtBtnProveedoresMouseClicked

    private void txtBtnComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnComprasMouseClicked
        dpPrincipal.removeAll();
        FrmCompra pnlCompra = new FrmCompra();
        dpPrincipal.add(pnlCompra).setVisible(true);
        jpCompras.setBackground(new Color(210, 210, 210));

        jpEmpleados.setBackground(new java.awt.Color(249, 249, 249));
        txtBtnEmpleados.setForeground(new java.awt.Color(153, 153, 153));
        jpProveedores.setBackground(new java.awt.Color(249, 249, 249));
        txtBtnProveedores.setForeground(new java.awt.Color(153, 153, 153));
        jpIngresosDiarios.setBackground(new java.awt.Color(249, 249, 249));
        txtBtnIngresosDiarios.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_txtBtnComprasMouseClicked

    private void txtBtnEmpleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnEmpleadosMouseEntered
        if (!jpEmpleados.getBackground().equals(color)) {
            jpEmpleados.setBackground(new Color(243, 243, 243));
            txtBtnEmpleados.setForeground(new Color(113, 113, 113));
        }
    }//GEN-LAST:event_txtBtnEmpleadosMouseEntered

    private void txtBtnEmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnEmpleadosMouseExited
        if (!jpEmpleados.getBackground().equals(color)) {
            jpEmpleados.setBackground(new Color(249, 249, 249));
            txtBtnEmpleados.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtBtnEmpleadosMouseExited

    private void txtBtnProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnProveedoresMouseEntered
        if (!jpProveedores.getBackground().equals(color)) {
            jpProveedores.setBackground(new Color(243, 243, 243));
            txtBtnProveedores.setForeground(new Color(113, 113, 113));
        }
    }//GEN-LAST:event_txtBtnProveedoresMouseEntered

    private void txtBtnProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnProveedoresMouseExited
        if (!jpProveedores.getBackground().equals(color)) {
            jpProveedores.setBackground(new Color(249, 249, 249));
            txtBtnProveedores.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtBtnProveedoresMouseExited

    private void txtBtnComprasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnComprasMouseEntered
        if (!jpCompras.getBackground().equals(color)) {
            jpCompras.setBackground(new Color(243, 243, 243));
            txtBtnCompras.setForeground(new Color(113, 113, 113));
        }
    }//GEN-LAST:event_txtBtnComprasMouseEntered

    private void txtBtnComprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnComprasMouseExited
        if (!jpCompras.getBackground().equals(color)) {
            jpCompras.setBackground(new Color(249, 249, 249));
            txtBtnCompras.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtBtnComprasMouseExited

    private void txtBtnIngresosDiariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnIngresosDiariosMouseClicked
        dpPrincipal.removeAll();
        FrmReporteIngresoDiario pnlIngresoDiario = new FrmReporteIngresoDiario();
        dpPrincipal.add(pnlIngresoDiario).setVisible(true);
        jpIngresosDiarios.setBackground(new Color(210, 210, 210));

        jpEmpleados.setBackground(new java.awt.Color(249, 249, 249));
        txtBtnEmpleados.setForeground(new java.awt.Color(153, 153, 153));
        jpProveedores.setBackground(new java.awt.Color(249, 249, 249));
        txtBtnProveedores.setForeground(new java.awt.Color(153, 153, 153));
        jpCompras.setBackground(new java.awt.Color(249, 249, 249));
        txtBtnCompras.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_txtBtnIngresosDiariosMouseClicked

    private void txtBtnIngresosDiariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnIngresosDiariosMouseEntered
        if (!jpIngresosDiarios.getBackground().equals(color)) {
            jpIngresosDiarios.setBackground(new Color(243, 243, 243));
            txtBtnIngresosDiarios.setForeground(new Color(113, 113, 113));
        }
    }//GEN-LAST:event_txtBtnIngresosDiariosMouseEntered

    private void txtBtnIngresosDiariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnIngresosDiariosMouseExited
        if (!jpIngresosDiarios.getBackground().equals(color)) {
            jpIngresosDiarios.setBackground(new Color(249, 249, 249));
            txtBtnIngresosDiarios.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtBtnIngresosDiariosMouseExited

    private void txtBtnIngresosDiarios3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnIngresosDiarios3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBtnIngresosDiarios3MouseClicked

    private void txtBtnIngresosDiarios3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnIngresosDiarios3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBtnIngresosDiarios3MouseEntered

    private void txtBtnIngresosDiarios3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnIngresosDiarios3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBtnIngresosDiarios3MouseExited

    private void txtBtnIngresosDiarios4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnIngresosDiarios4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBtnIngresosDiarios4MouseClicked

    private void txtBtnIngresosDiarios4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnIngresosDiarios4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBtnIngresosDiarios4MouseEntered

    private void txtBtnIngresosDiarios4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnIngresosDiarios4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBtnIngresosDiarios4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Principa().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Principa().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane dpPrincipal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpBarraLateral;
    private javax.swing.JPanel jpCompras;
    private javax.swing.JPanel jpEmpleados;
    private javax.swing.JPanel jpHeader;
    private javax.swing.JPanel jpIngresosDiarios;
    private javax.swing.JPanel jpIngresosDiarios1;
    private javax.swing.JPanel jpIngresosDiarios2;
    private javax.swing.JPanel jpMantenimiento;
    private javax.swing.JPanel jpProveedores;
    private javax.swing.JPanel jpReportes;
    private javax.swing.JPanel jpSalir;
    private javax.swing.JLabel lblDni;
    public static javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblmantenimiento;
    private javax.swing.JLabel lblmantenimiento1;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JLabel txtBtnCompras;
    private javax.swing.JLabel txtBtnEmpleados;
    private javax.swing.JLabel txtBtnIngresosDiarios;
    private javax.swing.JLabel txtBtnIngresosDiarios3;
    private javax.swing.JLabel txtBtnIngresosDiarios4;
    private javax.swing.JLabel txtBtnProveedores;
    private javax.swing.JLabel txtBtnSalir;
    // End of variables declaration//GEN-END:variables
}
